"""empty message

Revision ID: 42b810c0019b
Revises: 9601d3ad4cf0
Create Date: 2020-05-22 01:15:13.707108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b810c0019b'
down_revision = '9601d3ad4cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_user_profiles', sa.Column('img_address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_user_profiles', 'img_address')
    # ### end Alembic commands ###
