"""empty message

Revision ID: 8ab5dec7bbb3
Revises: d6d522b5a5f4
Create Date: 2020-05-22 19:14:13.329828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab5dec7bbb3'
down_revision = 'd6d522b5a5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('follows_follower_id_key', 'follows', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('follows_follower_id_key', 'follows', ['follower_id'])
    # ### end Alembic commands ###
