"""empty message

Revision ID: 912781c3b256
Revises: 6b0bacb93daf
Create Date: 2020-05-25 15:34:56.527090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912781c3b256'
down_revision = '6b0bacb93daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
