"""empty message

Revision ID: 9c7f4a686489
Revises: 912781c3b256
Create Date: 2020-05-26 07:10:10.055104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7f4a686489'
down_revision = '912781c3b256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_user_profiles', sa.Column('biography', sa.String(length=255), nullable=True))
    op.add_column('new_user_profiles', sa.Column('location', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_user_profiles', 'location')
    op.drop_column('new_user_profiles', 'biography')
    # ### end Alembic commands ###
